from lively_ik.configuration.updaters.basic import *
from lively_ik.configuration.updaters.collision import *
from lively_ik.configuration.updaters.behaviors import *
from lively_ik.configuration.updaters.meta import *
from lively_ik.configuration.updaters.validity import *

FIELDS = {
    # Rust-Based Fields
    'valid_solver':{
        'default':False,
        'derivation':derive_valid_solver,
        'dependencies':['control'],
        'on_change':{},
        'force':True,
        'guards':['valid_config']
    },
    'solver':{
        'default':None,
        'derivation':derive_solver,
        'dependencies':['valid_solver'],
        'on_change':{},
        'force':False,
        'guards':['valid_config']
    },
    'valid_config':{
        'default':False,
        'derivation':derive_valid_config,
        'dependencies':['solver'],
        'on_change':{},
        'force':True,
        'guards':['valid_nn']
    },
    'config':{
        'default':None,
        'derivation':derive_config,
        'dependencies':['valid_config'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot_output','valid_nn']
    },
    # Behavior-Based Fields
    # By default, add simple non-robot specific objectives
    'modes':{
        'default':[{'name':'default','weights':[1.0,1.0,0.1,2.0,5.0]}],
        'derivation':None,
        'dependencies':['config','target_weights'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'goals':{
        'default':[{'name':'default','values':[{},{},{},{},{}]}],
        'derivation':derive_goals,
        'dependencies':['config','target_goals'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'objectives':{
        'default':[{'tag': 'Minimize Velocity', 'variant': 'min_velocity', 'indices': []},
                   {'tag': 'Minimize Acceleration', 'variant': 'min_acceleration', 'indices': []},
                   {'tag': 'Minimize Jerk', 'variant': 'min_jerk', 'indices': []},
                   {'tag': 'Joint Limits', 'variant': 'joint_limits', 'indices': []},
                   {'tag': 'Self-Collision', 'variant': 'nn_collision', 'indices': []}],
        'derivation':None,
        'dependencies':['markers','config','target_weights','target_goals'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    # Neural-Network Fields
    'valid_nn':{
        'default':False,
        'derivation':derive_valid_nn,
        'dependencies':['nn_progress','config'],
        'on_change':{},
        'force':True,
        'guards':['valid_robot','nn_main_utd','nn_jointpoint_utd']
    },
    'nn_main_utd':{
        'default':False,
        'derivation':None,
        'dependencies':[],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'nn_jointpoint_utd':{
        'default':False,
        'derivation':None,
        'dependencies':[],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'nn_jointpoint':{
        'default':{'intercepts':[],'coefs':[],'split_point':None},
        'derivation':derive_nn_jointpoint,
        'dependencies':['nn_progress','valid_nn'],
        'on_change':{'nn_jointpoint_utd':True},
        'force':True,
        'guards':['valid_robot']
    },
    'nn_main':{
        'default':{'intercepts':[],'coefs':[],'split_point':None},
        'derivation':derive_nn_main,
        'dependencies':['nn_progress','valid_nn'],
        'on_change':{'nn_main_utd':True},
        'force':True,
        'guards':['valid_robot']
    },
    'training_scores':{
        'default':[],
        'derivation':derive_training_scores,
        'dependencies':['nn_progress'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'training_frames':{
        'default':[],
        'derivation':derive_training_frames,
        'dependencies':['nn_progress','nn_jointpoint'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'training_samples':{
        'default':[],
        'derivation':derive_training_samples,
        'dependencies':['nn_progress','training_scores','nn_main','training_frames'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'collision_graph':{
        'default':None,
        'derivation':derive_collision_graph,
        'dependencies':['nn_progress','training_samples'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'states':{
        'default':[],
        'derivation':None,
        'dependencies':[],
        'on_change':{'valid_nn':False,
                     'nn_main':{'intercepts':[],'coefs':[],'split_point':None},
                     'nn_jointpoint':{'intercepts':[],'coefs':[],'split_point':None},
                     'nn_main_utd':False,
                     'nn_jointpoint_utd':False,
                     'collision_graph':None,
                     'training_samples':[],
                     'training_frames':[],
                     'training_scores':[]
                     },
        'force':False,
        'guards':['valid_robot']
    },
    'static_environment':{
        'default':{
                'cuboids':[],
                'spheres':[],
                'pcs':[]
            },
        'derivation':None,
        'dependencies':['markers'],
        'on_change':{'valid_nn':False,
                     'nn_main':{'intercepts':[],'coefs':[],'split_point':None},
                     'nn_jointpoint':{'intercepts':[],'coefs':[],'split_point':None},
                     'nn_main_utd':False,
                     'nn_jointpoint_utd':False,
                     'collision_graph':None,
                     'training_samples':[],
                     'training_frames':[],
                     'training_scores':[]
                     },
        'force':False,
        'guards':['valid_urdf']
    },
    'robot_link_radius':{
        'default':0.05,
        'derivation':None,
        'dependencies':['markers'],
        'on_change':{'valid_nn':False,
                     'nn_main':{'intercepts':[],'coefs':[],'split_point':None},
                     'nn_jointpoint':{'intercepts':[],'coefs':[],'split_point':None},
                     'nn_main_utd':False,
                     'nn_jointpoint_utd':False,
                     'collision_graph':None,
                     'training_samples':[],
                     'training_frames':[],
                     'training_scores':[]
                     },
        'force':False,
        'guards':[]
    },
    # Robot-Derived Fields
    'starting_config':{
        'default':[],
        'derivation':derive_starting_config,
        'dependencies':['displayed_state','config','goals'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'valid_robot_output':{
        'default':[],
        'derivation':derive_valid_robot_output,
        'dependencies':['starting_config','config'],
        'on_change':{},
        'force':True,
        'guards':['valid_robot']
    },
    'axis_types':{
        'default':[],
        'derivation':derive_axis_types,
        'dependencies':['valid_robot_output'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'joint_limits':{
        'default':[],
        'derivation':derive_joint_limits,
        'dependencies':['valid_robot_output'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'joint_types':{
        'default':[],
        'derivation':derive_joint_types,
        'dependencies':['valid_robot_output'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'velocity_limits':{
        'default':[],
        'derivation':derive_velocity_limits,
        'dependencies':['valid_robot_output'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'rot_offsets':{
        'default':[],
        'derivation':derive_rot_offsets,
        'dependencies':['valid_robot_output'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'disp_offsets':{
        'default':[],
        'derivation':derive_disp_offsets,
        'dependencies':['valid_robot_output'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'displacements':{
        'default':[],
        'derivation':derive_displacements,
        'dependencies':['valid_robot_output'],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    # Robot-Based Fields
    'valid_robot':{
        'default':False,
        'derivation':derive_valid_robot,
        'dependencies':['axis_types','joint_types','joint_limits',
                        'rot_offsets','velocity_limits','disp_offsets',
                        'displacements','states','objectives','modes',
                        'goals','joint_poses'],
        'on_change':{},
        'force':True,
        'guards':['valid_arms']
    },
    'robot':{
        'default':None,
        'derivation':derive_robot,
        'dependencies':['valid_robot'],
        'on_change':{'nn_main_utd':False,'nn_jointpoint_utd':False},
        'force':False,
        'guards':['valid_arms']
    },
    'valid_arms':{
        'default':False,
        'derivation':derive_valid_arms,
        'dependencies':['robot'],
        'on_change':{},
        'force':True,
        'guards':['valid_urdf']
    },
    'extra_joints':{
        'default':{},
        'derivation':derive_extra_joints,
        'dependencies':['valid_arms'],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    'ee_fixed_joints':{
        'default':[],
        'derivation':derive_ee_fixed_joints,
        'dependencies':['valid_arms'],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    'fixed_frame':{
        'default':'base_link',
        'derivation':derive_fixed_frame,
        'dependencies':['joint_names'],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    'joint_ordering':{
        'default':[],
        'derivation':derive_joint_ordering,
        'dependencies':['extra_joints'],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    'joint_names':{
        'default':[],
        'derivation':derive_joint_names,
        'dependencies':['joint_ordering','extra_joints'],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    # Simple URDF Fields
    'links':{
        'default':[],
        'derivation':derive_links,
        'dependencies':['show_link_collision','markers'],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    'fixed_joints':{
        'default':[],
        'derivation':derive_fixed_joints,
        'dependencies':[],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    'dynamic_joints':{
        'default':[],
        'derivation':derive_dynamic_joints,
        'dependencies':[],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    'robot_tree':{
        'default':[],
        'derivation':derive_robot_tree,
        'dependencies':['fixed_frame','joint_ordering','ee_fixed_joints'],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    'valid_urdf':{
        'default':False,
        'derivation':derive_valid_urdf,
        'dependencies':['links','fixed_joints','dynamic_joints','robot_tree'],
        'on_change':{},
        'force':True,
        'guards':[]
    },
    'parsed_urdf':{
        'default':None,
        'derivation':derive_parsed_urdf,
        'dependencies':['valid_urdf'],
        'on_change':{},
        'force':False,
        'guards':[]
    },
    'urdf':{
        'default':'<?xml version="1.0" ?><robot name="default" xmlns:xacro="http://www.ros.org/wiki/xacro"><link name="base_link"/><joint name="default_joint" type="fixed"><parent link="base_link" /><child link="default_link" /><origin xyz="0 0 0" rpy="0 0 0" /></joint><link name="default_link"/></robot>',
        'derivation':None,
        'dependencies':['parsed_urdf'],
        'on_change':{},
        'force':False,
        'guards':[]
    },
    # Misc Fields
    'base_link_motion_bounds':{
        'default':[[0,0],[0,0],[0,0]],
        'derivation':None,
        'dependencies':['config'],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    'mode_control':{
        'default':'absolute',
        'derivation':None,
        'dependencies':['config'],
        'on_change':{},
        'force':False,
        'guards':[]
    },
    'mode_environment':{
        'default':'ECAA',
        'derivation':None,
        'dependencies':['config'],
        'on_change':{},
        'force':False,
        'guards':[]
    },
    # GUI Fields
    'displayed_state':{
        'default':[],
        'derivation':derive_displayed_state,
        'dependencies':[],
        'on_change':{},
        'force':False,
        'guards':[]
    },
    'control':{
        'default':'manual',
        'derivation':derive_control,
        'dependencies':[],
        'on_change':{},
        'force':False,
        'guards':[]
    },
    'selected':{
        'default':None,
        'derivation':None,
        'dependencies':['markers','active_mode'],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    'markers':{
        'default':{},
        'derivation':derive_markers,
        'dependencies':[],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    'show_link_collision':{
        'default':False,
        'derivation':None,
        'dependencies':['markers'],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    'active_mode':{
        'default':'default',
        'derivation':derive_active_mode,
        'dependencies':['target_weights'],
        'on_change':{},
        'force':False,
        'guards':['valid_config']
    },
    'active_goals':{
        'default':'default',
        'derivation':derive_active_goals,
        'dependencies':['target_goals'],
        'on_change':{},
        'force':False,
        'guards':['valid_config']
    },
    'joint_poses':{
        'default':[],
        'derivation':derive_joint_poses,
        'dependencies':[],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'target_weights':{
        'default':[1.0,1.0,0.1,2.0,5.0],
        'derivation':derive_target_weights,
        'dependencies':[],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'target_goals':{
        'default':[{},{},{},{},{}],
        'derivation':derive_target_goals,
        'dependencies':[],
        'on_change':{},
        'force':False,
        'guards':['valid_robot']
    },
    'highlights':{
        'default':[],
        'derivation':None,
        'dependencies':['markers'],
        'on_change':{},
        'force':False,
        'guards':['valid_urdf']
    },
    'nn_progress':{
        'default':0,
        'derivation':derive_nn_progress,
        'dependencies':[],
        'on_change':{},
        'force':False,
        'guards':['valid_robot_output']
    }
}
